" Note: Skip initialization for vim-tiny or vim-small.
if !1 | finish | endif

if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

 " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

 " Required:
 call neobundle#begin(expand('~/.vim/bundle/'))

 " Let NeoBundle manage NeoBundle
 " Required:
 NeoBundleFetch 'Shougo/neobundle.vim'

 " My Bundles here:
 " Refer to |:NeoBundle-examples|.
 " Note: You don't set neobundle setting in .gvimrc!

NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'tpope/vim-sensible' 
NeoBundle 'ervandew/supertab'
NeoBundle 'kien/rainbow_parentheses.vim'
NeoBundle 'derekwyatt/vim-scala'
NeoBundle 'mpollmeier/vim-scalaConceal'
NeoBundle 'godlygeek/tabular'
NeoBundle 'plasticboy/vim-markdown'

 call neobundle#end()

 " Required:
 filetype plugin indent on

 " If there are uninstalled bundles found on startup,
 " this will conveniently prompt you to install them.
 NeoBundleCheck

 set laststatus=2
 let g:airline#extensions#tabline#enabled=1
 set guifont=Consolas:h11:cDEFAULT
 let g:airline_powerline_fonts=1

 colorscheme wombat

 syntax on
