apiVersion: apps/v1
kind: Deployment
metadata:
  name: diy-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      project: diy
  template:
    metadata:
      labels:
        project: diy
    spec: 
      containers:
      - name: qsk-pod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        image: educative1/qsk-course:1.0

